name=circuit_kit_library
version=0.0.1
author=opilat
maintainer=opilat <ondrej.pilat@ozobot.com>
sentence=Ozobot circuit kit library
category=Other
url=https://github.com/ozobot/circuit_kit_library
architectures=*
includes=sensors.h
depends=Wire