name=drvkit_library
version=0.0.2
author=opilat
maintainer=opilat <ondrej.pilat@ozobot.com>
sentence=Ozobot DRVKit library
category=Other
url=https://github.com/ozobot/drvkit_library
architectures=*
includes=drvkit.h
depends=Wire, CRC32, AT24C
paragraph=HAL for the Ozobot DRVKit platform. It defines structures and objects for interacting with diverse sensor suite like proximity sensors, line following etc.