name=circuit_kit_library
version=0.0.2
author=opilat
maintainer=opilat <ondrej.pilat@ozobot.com>
sentence=Ozobot circuit kit library
category=Other
url=https://github.com/ozobot/circuit_kit_library
architectures=*
includes=circuit_kit.h
depends=Wire, CRC32, AT24C
paragraph=HAL for the Ozobot circuit kit platform. It defines structures and object for interacting with diverse sensor suite like proximity sensors, line following etc.